<?php
// Optimised version: Bundles all ships into one file to avoid HTTP/2 request overload
// 12.2025 - Refactored to generate single shipsCombined.js
// 04.2026 - Added compactShipForStaticJson() to strip default/empty values (Optimisation #4)

ob_start("ob_gzhandler"); 	
define('IN_STATIC_GENERATION', true);
// __DIR__-based so the script is CWD-independent: a docker exec without
// -w /usr/src/current would otherwise silently write into the container-local
// throwaway tree (see AUTOLOAD_GENERATOR_PLAN.md section 1c).
include_once __DIR__ . '/source/public/global.php';

// Compaction now lives in ONE shared place (ShipCompactor) so this generator and
// generateStaticShipFileWeb.php can no longer drift apart. They already HAD drifted:
// eight keys were stripped locally and kept live until 2026-08-01, so the live server
// shipped a bigger file to every visitor than this box ever produced. Explicit
// require_once because source/autoload.php is an autogenerated classmap ("do not edit").
require_once __DIR__ . '/source/server/lib/ShipCompactor.php';

/**
 * Encode a faction's ship data with default-value stripping applied.
 * $data is keyed by phpclass => ship object.
 */
function encodeCompactFactionData(array $data, int $flags = 0): string {
    $compacted = [];
    foreach ($data as $phpclass => $ship) {
        $compacted[$phpclass] = ShipCompactor::compactShipObject($ship);
    }
    return json_encode($compacted, $flags | JSON_PARTIAL_OUTPUT_ON_ERROR | JSON_UNESCAPED_UNICODE);
}

// ----------------------
// High Resource Limits
// ----------------------
ini_set('memory_limit', '-1'); 
set_time_limit(300);

$fileBase = __DIR__ . '/source/public/static/ships';

/* ─── shipsCombined.js generation DISABLED (08.2026) ─────────────────────────────────
 *
 * NOTHING LOADS IT. static/ships.php (the <script> tag that pulled it in) is included by
 * no page: both call sites were commented out in Dec 2025 —
 *     source/public/game.php:105       //include 'static/ships.php';
 *     source/public/gamelobby.php:128  //include 'static/ships.php';
 * A search for "shipsCombined" across every .php/.js/.html and the built bundles finds
 * only those two commented lines. The file was ~99MB, rebuilt on every deploy, and served
 * to nobody.
 *
 * WHAT REPLACED IT (both still generated below / elsewhere):
 *   - Lobby : per-faction static/json/<faction>.json, fetched on demand via
 *             gamelobbyloader.php with a ?v=<filemtime> cache-buster.
 *   - Game  : game.php builds window.staticShips INLINE per request from
 *             ShipLoader::getShipsByClass(), covering only the classes in that game.
 *
 * TO RESTORE: un-comment the three blocks marked [shipsCombined] in this file (and the
 * matching ones in generateStaticShipFileWeb.php), then re-enable the include in game.php
 * / gamelobby.php. The .htaccess brotli rewrite already handles shipsCombined.js.br, so
 * nothing is needed there.
 *
 * [shipsCombined] 1/3 — create + seed the bundle
 * $combinedFile = $fileBase . 'Combined.js';
 * file_put_contents($combinedFile, 'window.staticShips = {};' . PHP_EOL);
 */

// Clear server-side cache (ShipLoader)
$cacheDir = sys_get_temp_dir() . '/fv_cache';
if (is_dir($cacheDir)) {
    $files = glob($cacheDir . '/*');
    foreach ($files as $file) {
        if (is_file($file)) {
            @unlink($file);
        }
    }
    print("Server-side cache cleared.\n");
}

// Ensure JSON directory exists
$jsonDir = __DIR__ . '/source/public/static/json';
if (!is_dir($jsonDir)) {
    mkdir($jsonDir, 0777, true);
}

// ----------------------
// OPTIMIZATION: Fetch ALL ships at once
// ----------------------
$shipsByFaction = ShipLoader::getAllShipsStatic(null);

if (!$shipsByFaction) {
    die("Error: No ships found.\n");
}

foreach($shipsByFaction as $factionName => $shipsOfFaction){
	$data = [];
	print($factionName . "\n");

    foreach ($shipsOfFaction as $ship) {
        if ($ship && $ship instanceof BaseShip) {
            print("generating: " . $ship->faction . " " . $ship->phpclass . "\n");
            $data[$ship->phpclass] = $ship;
        }
    }
	
    // Use compact encoding to strip default/empty values (Optimisation #4)
    $compactJson = encodeCompactFactionData($data, JSON_NUMERIC_CHECK);

    /* [shipsCombined] 2/3 — append this faction to the bundle
     * $chunk = 'window.staticShips["' . $factionName . '"]=' . $compactJson . ';' . PHP_EOL;
     * file_put_contents($combinedFile, $chunk, FILE_APPEND);
     */

    // Save pure JSON for server-side caching (Game Lobby) — THIS is the file the lobby
    // actually fetches, via gamelobbyloader.php.
    $jsonPath = $jsonDir . '/' . $factionName . '.json';
    $jsonPayload = [$factionName => json_decode($compactJson, true)];
    file_put_contents($jsonPath, json_encode($jsonPayload, JSON_NUMERIC_CHECK | JSON_PARTIAL_OUTPUT_ON_ERROR | JSON_UNESCAPED_UNICODE));
    ShipCompactor::precompressBrotli($jsonPath); // .json.br; no-op without the extension

    $data = null; // free memory
}

/* [shipsCombined] 3/3 — pre-compress the bundle and point ships.php at it
 * ShipCompactor::precompressBrotli($combinedFile);
 * $fileName = $fileBase . '.php'; // source/public/static/ships.php
 * $includeText = '<script src="static/shipsCombined.js?v=' . time() . '"></script>';
 * file_put_contents($fileName, $includeText);
 */

print("\n ships generated!\n\n");