<?php
/**
 * AutomatedMovement — server-side movement generation for units the player does not
 * control this turn.
 *
 * First caller: Uncontrolled Hunter-Killer flights (HK Jamming, Strategy B = drift).
 * Designed as the seam for future CPU-controlled ships: the MECHANICS here (reading a
 * unit's movement "intent", building MovementOrders, the drift primitive, and later
 * course-plotting + ram-on-contact) are generic; the DECISION of what a unit wants
 * ("drift", or eventually "ram nearest enemy of size X") is supplied by the unit via
 * getAutomatedMovementIntent(). Keep ship-specific policy OUT of this handler.
 *
 * Currently implemented intents:
 *   'drift' — continue current heading at current speed (straight-line). No turning.
 *             Optionally jinks at intent['jink'] levels (costs 1 thrust/level).
 *             Fallback when 'seek' has no target.
 *   'seek'  — pursue the nearest enemy ship and ram on contact. Thrust order: jink first,
 *             then accel/decel up to HALF the remaining thrust to close the gap, then the
 *             rest on turning toward the target (greedy per-hex). Used for Uncontrolled HKs.
 *
 * Movement model (flights): a flight lays `speed` "move" orders (one hex each along the
 * current heading); "turnleft"/"turnright" change heading by one hex-side; "speedchange"
 * changes speed; "jink" adds an evasion level. All cost thrust from freethrust. Flights
 * have turndelaycost 0 (no turn delay), so the only turning constraint is thrust budget.
 *
 * Called from MovementGamePhase::advance in place of the plain dummy-'end' move for any
 * unit whose isUnderAutomatedControl() is true.
 */
class AutomatedMovement
{
    /* True when this unit's movement should be generated by the server this turn rather
     * than taken from player input. Cheap-guarded on remoteControl so ordinary units
     * short-circuit immediately (remoteControl is very rare). Extend the condition here
     * (not at call sites) as new automated-control sources are added. */
    public static function isUnderAutomatedControl($ship, $gamedata)
    {
        if (!empty($ship->remoteControl) && self::isUncontrolled($ship, $gamedata)) {
            return true;
        }
        return false;
    }

    /* A remoteControl flight is Uncontrolled this turn if its sample fighter carries an
     * Uncontrolled crit in effect now. The crit is a oneturn crit placed on turn T
     * (effect T+1); hasCritical's oneturn handling matches it on the effect turn. */
    private static function isUncontrolled($flight, $gamedata)
    {
        if (!($flight instanceof FighterFlight)) return false;
        $sample = $flight->getSampleFighter();
        if (!$sample) return false;
        return $sample->hasCritical("Uncontrolled", $gamedata->turn) > 0;
    }

    /* Generate and SUBMIT this turn's movement for an automated unit. Returns the
     * MovementOrder array submitted (for the caller's in-memory sync), or null when the
     * unit has no prior movement to extrapolate from (shouldn't happen post-deployment). */
    public static function generateAndSubmit($ship, $gamedata, $dbManager)
    {
        $intent = $ship->getAutomatedMovementIntent($gamedata);

        switch ($intent['type']) {
            case 'seek':
                $moves = self::buildSeekMove($ship, $gamedata, $intent);
                break;
            case 'drift':
            default:
                $moves = self::buildDriftMove($ship, $gamedata, $intent);
                break;
        }

        if (empty($moves)) return null;

        $dbManager->submitMovement($gamedata->id, $ship->id, $gamedata->turn, $moves);
        $ship->movement = array_merge($ship->movement, $moves);
        return $moves;
    }

    /* DRIFT: an 'end' order at the position reached by continuing the last heading at
     * the last speed. Position is absolute (getHexPos reads the final order's position),
     * so we advance the previous hex by `speed` steps along `heading` via the cube
     * primitive. Heading/facing/speed are unchanged — the unit coasts in a straight line.
     *
     * Jinking ($intent['jink'] levels): the unit jinks at its default level while
     * uncontrolled. Jinking costs 1 thrust per level; FV models each level as its own
     * "jink" MovementOrder with value 1 and requiredThrust/assignedThrust [1,0,0,0,0]
     * (mirrors movement.js doJink for flights). getJinking sums the value across them. */
    private static function buildDriftMove($ship, $gamedata, $intent)
    {
        $lastMove = $ship->getLastMovement();
        if (!$lastMove) return array();

        $speed   = (int)$lastMove->speed;
        $heading = (int)$lastMove->heading;
        $facing  = (int)$lastMove->facing;

        $newPos = self::advanceHex($lastMove->position, $heading, $speed);

        $moves = array();

        $end = new MovementOrder(
            null, 'end', $newPos, 0, 0,
            $speed, $heading, $facing,
            false, $gamedata->turn, 0, $ship->iniative
        );
        $moves[] = $end;

        $jink = isset($intent['jink']) ? (int)$intent['jink'] : 0;
        for ($i = 0; $i < $jink; $i++) {
            $jinkMove = new MovementOrder(
                null, 'jink', $newPos, 0, 0,
                $speed, $heading, $facing,
                false, $gamedata->turn, 1, $ship->iniative //value 1 = one jink level
            );
            $jinkMove->requiredThrust = array(1, 0, 0, 0, 0);
            $jinkMove->assignedThrust = array(1, 0, 0, 0, 0);
            $moves[] = $jinkMove;
        }

        return $moves;
    }

    /* Advance an OffsetCoordinate by $steps hexes along heading direction (0-5).
     * Returns a fresh OffsetCoordinate. $steps 0 returns an equivalent position. */
    public static function advanceHex($position, $heading, $steps)
    {
        $offset = ($position instanceof OffsetCoordinate) ? $position : new OffsetCoordinate($position);
        if ($steps <= 0) return new OffsetCoordinate($offset->q, $offset->r);

        $cube = $offset->toCube();
        for ($i = 0; $i < $steps; $i++) {
            $cube = $cube->moveToDirection($heading);
        }
        return $cube->toOffset();
    }

    /* ---------------------------------------------------------------------------
     * SEEK (Strategy A): pursue the nearest enemy ship and ram on contact.
     *
     * Thrust budget order (per design):
     *   1. JINK     — intent['jink'] levels, 1 thrust each.
     *   2. ACCEL    — change speed toward the gap, capped at HALF the thrust left
     *                 after jinking (1 thrust per ±1 speed).
     *   3. TURNING  — whatever thrust remains; spent greedily turning toward the
     *                 target's bearing per hex of travel.
     *
     * The route is then `speed` hexes long (flights must spend their whole speed in
     * movement). Greedy per-hex: before each move-hex, rotate heading one step toward
     * the direction that most reduces distance to the target, if a turn is affordable.
     * Falls back to drift when there is no enemy to chase.
     * --------------------------------------------------------------------------- */
    private static function buildSeekMove($ship, $gamedata, $intent)
    {
        $lastMove = $ship->getLastMovement();
        if (!$lastMove) return array();

        $target = self::findNearestEnemy($ship, $gamedata);
        if (!$target) {
            // No one to chase — coast straight (still jinks).
            return self::buildDriftMove($ship, $gamedata, $intent);
        }

        $jink = isset($intent['jink']) ? (int)$intent['jink'] : 0;
        $thrustTotal = (int)$ship->freethrust;

        // 1. Jink budget (clamped to what's available).
        $jink = max(0, min($jink, $thrustTotal));
        $thrustAfterJink = $thrustTotal - $jink;

        // 2. Accel/decel: half of the post-jink thrust, applied toward closing the gap.
        $accelBudget = intdiv($thrustAfterJink, 2);
        $startSpeed  = (int)$lastMove->speed;
        $targetCube  = $target->getHexPos()->toCube();
        $startCube   = $lastMove->position->toCube();
        $gap         = $startCube->distanceTo($targetCube);

        // Want enough speed to reach the target this turn, but no more (overshoot wastes
        // the ram). Clamp the change to the accel budget and to a sane 0..speedCap range.
        $desiredSpeed = max(0, min($gap, self::SPEED_CAP));
        $speedDelta   = $desiredSpeed - $startSpeed;
        if ($speedDelta >  $accelBudget) $speedDelta =  $accelBudget;
        if ($speedDelta < -$accelBudget) $speedDelta = -$accelBudget;
        $newSpeed     = max(0, $startSpeed + $speedDelta);
        $accelSpent   = abs($speedDelta);

        // 3. Remaining thrust is for turning.
        $turnThrust = $thrustAfterJink - $accelSpent;

        $moves   = array();
        $heading = (int)$lastMove->heading;
        $facing  = $heading; // flights keep facing == heading
        $pos     = $lastMove->position;
        $iniative = $ship->iniative;

        // Acceleration order (one combined 'speedchange'); thrust = abs(delta).
        if ($speedDelta !== 0) {
            $accel = new MovementOrder(
                null, 'speedchange', $pos, 0, 0,
                $newSpeed, $heading, $facing,
                false, $gamedata->turn, $speedDelta, $iniative
            );
            $accel->requiredThrust = array($accelSpent, 0, 0, 0, 0);
            $accel->assignedThrust = array($accelSpent, 0, 0, 0, 0);
            $moves[] = $accel;
        }

        // Walk the route: `newSpeed` hexes, turning toward the target as thrust allows.
        for ($step = 0; $step < $newSpeed; $step++) {
            // Turn toward the target before moving (greedy: as many single-side turns as
            // afford and as needed to face the best direction). Bounded to 3 single-side
            // turns (max rotation to any of 6 directions) as defensive insurance.
            $desiredDir = self::bestDirectionToward($pos, $target, $gamedata);
            $turnGuard = 0;
            while ($heading !== $desiredDir && $turnGuard < 3) {
                $turnGuard++;
                $turnCost = self::turnCost($ship, $newSpeed);
                if ($turnCost > $turnThrust) break; // out of turning thrust
                $right = self::turnSideToward($heading, $desiredDir); // +1 right, -1 left
                $heading = Mathlib::addToHexFacing($heading, $right);
                $facing  = $heading;
                $turnThrust -= $turnCost;

                $turn = new MovementOrder(
                    null, ($right > 0 ? 'turnright' : 'turnleft'), $pos, 0, 0,
                    $newSpeed, $heading, $facing,
                    false, $gamedata->turn, 0, $iniative
                );
                $turn->requiredThrust = array($turnCost, 0, 0, 0, 0);
                $turn->assignedThrust = array($turnCost, 0, 0, 0, 0);
                $moves[] = $turn;

                // Re-evaluate the best direction from the (unchanged) hex after turning.
                $desiredDir = self::bestDirectionToward($pos, $target, $gamedata);
            }

            // Move one hex along the (possibly updated) heading.
            $pos = self::advanceHex($pos, $heading, 1);
            $move = new MovementOrder(
                null, 'move', $pos, 0, 0,
                $newSpeed, $heading, $facing,
                false, $gamedata->turn, 0, $iniative
            );
            $moves[] = $move;
        }

        // Terminal 'end' at the final hex.
        $end = new MovementOrder(
            null, 'end', $pos, 0, 0,
            $newSpeed, $heading, $facing,
            false, $gamedata->turn, 0, $iniative
        );
        $moves[] = $end;

        // Jink orders (after the route is laid; they sit at the final position like the
        // drift builder, and getJinking just sums their value across the turn).
        for ($i = 0; $i < $jink; $i++) {
            $jinkMove = new MovementOrder(
                null, 'jink', $pos, 0, 0,
                $newSpeed, $heading, $facing,
                false, $gamedata->turn, 1, $iniative
            );
            $jinkMove->requiredThrust = array(1, 0, 0, 0, 0);
            $jinkMove->assignedThrust = array(1, 0, 0, 0, 0);
            $moves[] = $jinkMove;
        }

        return $moves;
    }

    const SPEED_CAP = 20; // sanity clamp on auto-pilot speed (well above any real flight)

    /* Nearest non-destroyed enemy SHIP (not terrain, not another flight/mine) to this
     * unit, by hex distance from the unit's current position. Null if none. */
    private static function findNearestEnemy($ship, $gamedata)
    {
        $best = null;
        $bestDist = PHP_INT_MAX;
        foreach ($gamedata->ships as $other) {
            if ($other->id === $ship->id) continue;
            if ($other->team === $ship->team) continue;
            if ($other->isDestroyed()) continue;
            if ($other->isTerrain()) continue;
            if ($other->mine) continue;
            if ($other->getTurnDeployed($gamedata) > $gamedata->turn) continue;

            $dist = Mathlib::getDistanceHex($ship, $other);
            if ($dist < $bestDist) {
                $bestDist = $dist;
                $best = $other;
            }
        }
        return $best;
    }

    /* The hex-direction (0-5) FROM $pos whose neighbour is closest to the target hex —
     * i.e. the heading that most reduces distance to the target. Greedy aim primitive. */
    private static function bestDirectionToward($pos, $target, $gamedata)
    {
        $targetCube = $target->getHexPos()->toCube();
        $fromCube   = (($pos instanceof OffsetCoordinate) ? $pos : new OffsetCoordinate($pos))->toCube();

        $bestDir = 0;
        $bestDist = PHP_INT_MAX;
        for ($dir = 0; $dir < 6; $dir++) {
            $neighbour = $fromCube->moveToDirection($dir);
            $dist = $neighbour->distanceTo($targetCube);
            if ($dist < $bestDist) {
                $bestDist = $dist;
                $bestDir = $dir;
            }
        }
        return $bestDir;
    }

    /* Shortest rotation side from $heading to $desired: +1 (right/CW) or -1 (left/CCW).
     * Returns +1 for an exact opposite (arbitrary but consistent). */
    private static function turnSideToward($heading, $desired)
    {
        $diff = (($desired - $heading) % 6 + 6) % 6; // 0..5 steps clockwise
        return ($diff <= 3) ? 1 : -1;
    }

    /* Per-single-side turn cost for a flight: ceil(speed * turncost), min 1. Mirrors
     * the client (movement.js canTurn). Flights have no turn-delay (turndelaycost 0). */
    private static function turnCost($ship, $speed)
    {
        $cost = (int)ceil($speed * $ship->turncost);
        return max(1, $cost);
    }

    /* ---------------------------------------------------------------------------
     * AUTO-RAM: an Uncontrolled HK that ended its (seek) movement in the SAME hex as
     * an enemy ship rams it. Ramming is range 0 only (RammingAttack range 0.1). Called
     * from Firing::prepareFiring (Fire phase, movement final) BEFORE ram orders are
     * gathered, so the normal ramming pipeline calculates + resolves each attack.
     *
     * EVERY LIVE FIGHTER in the flight rolls its own ram (one ram FireOrder per fighter,
     * each on that fighter's own RammingAttack) — same as a player-targeted flight ram,
     * where each fighter's ramming weapon is a separate fire order. The target is the
     * nearest co-located enemy; the whole flight piles onto it.
     *
     * Player HKs ram via player-submitted fire orders; this is the no-player path.
     * Cheap-guarded on remoteControl so the scan skips ordinary ships immediately.
     * --------------------------------------------------------------------------- */
    public static function createAutomatedRamOrders($gamedata)
    {
        foreach ($gamedata->ships as $flight) {
            if (empty($flight->remoteControl)) continue;
            if (!self::isUncontrolled($flight, $gamedata)) continue;
            if ($flight->isDestroyed()) continue;

            // Pick one co-located enemy ship for the whole flight to ram (range 0).
            $enemy = self::firstCoLocatedEnemy($flight, $gamedata);
            if (!$enemy) continue;

            // One ram per LIVE fighter, on that fighter's own RammingAttack. Only the
            // first order carries the announcement note so the combat log shows it once.
            $firstRam = true;
            foreach ($flight->systems as $fighter) {
                if (!($fighter instanceof Fighter)) continue;
                if ($fighter->isDestroyed($gamedata->turn)) continue;

                $ram = null;
                foreach ($fighter->systems as $sub) {
                    if (!empty($sub->isRammingAttack)) { $ram = $sub; break; }
                }
                if (!$ram) continue;
                if ($ram->checkAlreadyRammed($enemy->id)) continue; // de-dupe per fighter

                $fireOrder = new FireOrder(
                    -1, "normal", $flight->id, $enemy->id,
                    $ram->id, -1, $gamedata->turn, 1,
                    0, 0, 1, 0, 0,
                    0, 0, 'Ramming', 10000
                );
                $fireOrder->addToDB = true;
                if ($firstRam) {
                    $fireOrder->pubnotes = "<br>Uncontrolled Hunter-Killers ram " . $enemy->name . "!";
                    $firstRam = false;
                }
                $ram->fireOrders[] = $fireOrder;
            }
        }
    }

    /* The nearest enemy ship sharing the flight's hex (range 0), or null. Same target
     * filters as findNearestEnemy; used so every fighter in the flight rams one ship. */
    private static function firstCoLocatedEnemy($flight, $gamedata)
    {
        $best = null;
        $bestDist = PHP_INT_MAX;
        foreach ($gamedata->ships as $enemy) {
            if ($enemy->id === $flight->id) continue;
            if ($enemy->team === $flight->team) continue;
            if ($enemy->isDestroyed()) continue;
            if ($enemy->isTerrain()) continue;
            if ($enemy->mine) continue;
            if ($enemy->getTurnDeployed($gamedata) > $gamedata->turn) continue;
            if (Mathlib::getDistanceHex($flight, $enemy) > 0) continue; // range 0 only

            // Tie-break by combat-value-ish proxy: just take the first / nearest.
            $best = $enemy;
            break;
        }
        return $best;
    }
}
