<?php
/**
 * Energy Draining Net linking — the Walkers of Sigma-957 distributed field.
 * WALKERS_OF_SIGMA_PLAN.md section 3.7 (Stage 7).
 *
 * WHAT IT DOES
 * An Energy Draining Net projects a field of radius ZERO: its own hex and nothing else. The
 * field it is actually for is generated BETWEEN Nets — "several vessels in formation, surveying
 * the environment between them". This class turns a fleet's Nets into the extra hexes that
 * belong to their team's field:
 *
 *   1. PAIRWISE. Two active Nets on the same team ending their movement at most LINK_RANGE
 *      hexes apart link, and the hexes BETWEEN them join the field.
 *   2. CLOSED-AREA FILL. FILL_MIN_NETS or more Nets linked into one group enclose an area, and
 *      that area may be filled in "as long as the filled-in hexes number less than double the
 *      total number of Energy Draining Nets" — i.e. at most 2N-1 hexes.
 *
 * ⭐ WHY IT PRODUCES HEXES AND NOTHING ELSE. Every consumer of an Energy Draining Field — the
 * targeting penalty, the drain at the Critical Hit step, own-fleet immunity, overlap collapse —
 * already reads TacGamedata::$edfHexes and asks nothing about where a hex came from. Handing
 * setEdfHexes() a list of hexes to fold into that same map is therefore the whole integration:
 * no consumer changed for Stage 7, exactly as none changed for the Stage 6 mine.
 *
 * ⭐⭐ IT RUNS IN setEdfHexes(), NOT IN THE EdfExposure RESOLVER — a deliberate departure from
 * the plan's section 3.7, which was written before Stage 4 built the map. The resolver runs at
 * the Critical Hit step, long after $edfHexes has been built AND PUBLISHED, so corridors
 * computed there would have drained units and been invisible to the targeting penalty, to the
 * client's mirror of it and to the map overlay — three of the four things a field is for. Built
 * here instead, every one of them is served by construction and the drain still sees the
 * corridors, because EdfExposure reads the same map.
 *
 * ⚠️ ORDER MATTERS AND IT IS FIXED: this runs AFTER setEdfHexes()' per-ship disc sweep, so that
 * "it is not necessary to count those hexes in an EDF generated by another vessel" is answered
 * by simply asking whether a hex is already in the map. That includes the Nets' OWN hexes, which
 * the disc sweep adds at radius 0 before this is called.
 *
 * ⚠️ DETERMINISM IS A HARD REQUIREMENT, NOT A NICETY. This runs on BOTH gamedata loads of one
 * request (plan trap 1), on every poll of every viewer, and again on every replay. Nothing here
 * may roll a die or depend on iteration order that the caller does not control: pairs are walked
 * in a sorted order, teams are ksort()ed, and the corridor tie-break ends in a rule that cannot
 * tie (see pickCorridor). The output has to be the same list of hexes every single time or the
 * server and the client would disagree about the to-hit penalty.
 */
class EdfNetLinks
{
    /* ================= EDN LINKING STATS — the rules text, 2026-09-05 ==================
         "Two vessels equipped with Nets that end their movement at most three hexes away from
          each other may extend the generated EDF to include the two hexes between them as well
          as their own hexes."                                        -> LINK_RANGE
         "If several ships linking up in such a manner form a closed area, the area may be
          'filled in' with an EDF as long as the filled-in hexes number less than double the
          total number of Energy Draining Nets."                      -> FILL_MIN_NETS, 2N-1
         "It is not necessary to count those hexes in an EDF generated by another vessel."
                                                                      -> the $coverage test
       ⚠️ "THE TWO HEXES BETWEEN THEM" IS THE RANGE-3 CASE, NOT A CONSTANT. At distance 3 there
       are two intervening hexes, at distance 2 there is one, and at distance 1 there are none —
       so the corridor is "the hexes strictly between", which generalises the sheet's wording
       instead of hard-coding its example. A pair of adjacent Nets therefore still LINKS (it
       counts towards a closed area) while contributing no corridor hexes of its own.
       ================================================================================== */
    const LINK_RANGE    = 3;    //"at most three hexes away from each other"
    const FILL_MIN_NETS = 3;    //a closed area needs three; two Nets are a corridor, not an area

    /* Defensive only. A fill's candidate hexes are swept out of the bounding box of one linked
       group, and a group's span is bounded by LINK_RANGE x (nets - 1) — so a real fleet cannot
       approach this. It exists so that a hull mounting an absurd number of Nets degrades into a
       logged no-fill rather than into a multi-second sweep on every gamedata load. */
    const MAX_FILL_SWEEP = 4000;
    /* ================================================================================== */

    /* Why a closed area was left unfilled, as an array of human-readable strings, rebuilt from
       scratch on every resolve(). Read by the Stage 7 harness and by anything that ever wants to
       show a player why their formation did not fill.

       ⚠️⚠️ THIS IS A STATIC ARRAY RATHER THAN A Debug::log() CALL, AND THE DIFFERENCE IS NOT
       STYLISTIC. setEdfHexes() runs on EVERY gamedata load - which is every poll of every viewer,
       twice per request - and Debug::log writes a timestamped block carrying the request method,
       URI, IP, the whole $_REQUEST and the whole $_SESSION to fieryvoid.log for each call. A
       fleet that parks in an over-cap formation is a PERSISTENT state, not an event, so logging
       it would dump the session of every watching player to disk every couple of seconds for as
       long as the ships sat there. An in-memory string costs nothing and says the same thing.
       ⚠️ Per-load and self-clearing, so it needs no DBManager reset (the trap section 2.1
       records): resolve() empties it before it does anything else, exactly as setEdfHexes()
       clears $edfPresent, so the double gamedata load cannot accumulate. */
    public static $refusals = array();

    /**
     * The hexes the Nets add to their teams' fields.
     *
     * @param  object $gamedata  TacGamedata — read only, for the unit positions the corridor
     *                           tie-break consults.
     * @param  array  $nets      array of array('ship'=>BaseShip, 'system'=>EnergyDrainingNet,
     *                           'pos'=>OffsetCoordinate, 'team'=>int) — ALREADY filtered by the
     *                           caller for destroyed / in-hyperspace / unpositioned units and
     *                           for isEdfActive(), because setEdfHexes() has to ask those
     *                           questions anyway.
     * @param  array  $edfHexes  the map as built so far ("q,r" => array('teams' => set)). Read
     *                           only: this method returns hexes, it does not add them.
     * @return array             array of array('q','r','team','shipId'), possibly empty.
     */
    public static function resolve($gamedata, array $nets, array $edfHexes)
    {
        self::$refusals = array();              //per-load, self-clearing - see the property

        if (count($nets) < 2) return array();   //nothing links to itself

        /* Live coverage. Seeded from the map the disc sweep built and updated as corridors are
           added, so a hex counts as "new" exactly once however many pairs would have produced
           it. PER TEAM, because an enemy's field over a hex does not spare this team the work of
           covering it — the rules' exemption is "an EDF generated by another vessel", i.e. one
           of yours. */
        $coverage = array();
        foreach ($edfHexes as $key => $entry) $coverage[$key] = $entry['teams'];

        $byTeam = array();
        foreach ($nets as $net) $byTeam[(int)$net['team']][] = $net;
        ksort($byTeam);                          //team order must not depend on the ship loop

        $occupancy = null;                       //built at most once, and only if a tie needs it
        $added = array();

        foreach ($byTeam as $team => $teamNets) {
            if (count($teamNets) < 2) continue;

            /* A STABLE ORDER FOR THE WHOLE TEAM, and everything below depends on it: pairs are
               walked in this order, the corridor tie-break's "which hexes are already covered"
               moves as they are walked, and a group's attribution takes the first member. Ship id
               is unique and never reused within a game; the system id breaks the tie for two Nets
               on one hull. */
            usort($teamNets, function($a, $b){
                if ($a['ship']->id != $b['ship']->id) return ($a['ship']->id < $b['ship']->id) ? -1 : 1;
                if ($a['system']->id != $b['system']->id) return ($a['system']->id < $b['system']->id) ? -1 : 1;
                return 0;
            });

            $count = count($teamNets);
            $links = array();                    //adjacency over indices into $teamNets

            /* ---- 1. Pairwise corridors ------------------------------------------------- */
            for ($i = 0; $i < $count; $i++) {
                for ($j = $i + 1; $j < $count; $j++) {
                    $distance = $teamNets[$i]['pos']->distanceTo($teamNets[$j]['pos']);
                    if ($distance > self::LINK_RANGE) continue;

                    //Linked for the purposes of a closed area even when there is no hex between
                    //them - two adjacent Nets are still "linking up in such a manner".
                    $links[$i][$j] = true;
                    $links[$j][$i] = true;

                    $shipId = (int)$teamNets[$i]['ship']->id;   //lower id of the pair, by the sort above

                    foreach (self::pickCorridor($gamedata, $teamNets[$i]['pos'], $teamNets[$j]['pos'],
                                                $team, $coverage, $occupancy) as $hex) {
                        self::addHex($added, $coverage, $hex, $team, $shipId);
                    }
                }
            }

            /* ---- 2. Closed-area fill ---------------------------------------------------- */
            self::fillClosedAreas($teamNets, $links, $team, $coverage, $added);
        }

        return $added;
    }

    /* ---------------------------------------------------------------- corridors ------ */

    /**
     * The hexes between two linked Nets — "the player may choose the hex that the field is
     * generated through", resolved deterministically because there is no UI to ask (plan D8).
     *
     * ⭐ THE RANKING IS TOWARD THE CORRIDOR A PLAYER WOULD ACTUALLY PICK, not an arbitrary one.
     * A field exists to drain enemies and to lengthen the corridor a shot has to cross, so:
     *   1. most ENEMY units standing in the corridor  — the obvious choice, and the only rule
     *      here that is about the game rather than about tidiness;
     *   2. most hexes NOT ALREADY covered by this team's field — adds the most new field;
     *   3. lowest (q, r), compared hex by hex — a pure stability tie-break, never a game rule.
     *
     * ⚠️ RULE 3 EXISTS SOLELY TO MAKE THE ORDER TOTAL, and dropping it would be a real bug
     * rather than a cosmetic one. Two candidate corridors that tie on 1 and 2 are extremely
     * ordinary (an empty board), and an unbroken tie would let PHP's iteration order decide —
     * which would be free to differ between the request's two gamedata loads, between two
     * viewers polling the same turn, and between a game and its replay. The client mirrors the
     * to-hit penalty off the published map, so "the corridor moved" reads as "the client's
     * predicted hit chance disagrees with the dice".
     */
    private static function pickCorridor($gamedata, $a, $b, $team, array &$coverage, &$occupancy)
    {
        $candidates = self::corridorCandidates($a, $b);
        if (empty($candidates)) return array();          //adjacent or same hex: nothing between
        if (count($candidates) === 1) return $candidates[0];

        //Only now is the tie-break's cost worth paying, and only once per request.
        if ($occupancy === null) $occupancy = self::buildOccupancy($gamedata);

        $best = null;
        $bestEnemies = -1;
        $bestNew = -1;

        foreach ($candidates as $path) {
            $enemies = 0;
            $new = 0;
            foreach ($path as $hex) {
                $key = $hex->q . ',' . $hex->r;
                if (isset($occupancy[$key])) {
                    foreach ($occupancy[$key] as $otherTeam => $units) {
                        if ((int)$otherTeam !== (int)$team) $enemies += $units;
                    }
                }
                if (!isset($coverage[$key][$team])) $new++;
            }

            if ($best === null
                || $enemies > $bestEnemies
                || ($enemies === $bestEnemies && $new > $bestNew)
                || ($enemies === $bestEnemies && $new === $bestNew && self::compareHexes($path, $best) < 0)) {
                $best = $path;
                $bestEnemies = $enemies;
                $bestNew = $new;
            }
        }

        return $best;
    }

    /**
     * Every shortest-path corridor between two hexes, as the list of hexes STRICTLY BETWEEN
     * them. Empty when they are adjacent or in the same hex.
     *
     * ⚠️ NOT HexZone::line(). That answers ONE line and includes both endpoints — it is the
     * right tool for "which hexes does this shot cross", and the wrong one here, where the rules
     * hand the player a CHOICE between corridors and the endpoints are the Nets themselves
     * (already field, at radius 0). The walk below enumerates all of them; at LINK_RANGE 3 that
     * is at most three candidates of two hexes each, so exhaustive enumeration is cheaper than
     * being clever about it.
     *
     * Each returned path is sorted, so compareHexes() gives a total order over candidates and
     * two spellings of one corridor cannot rank differently.
     */
    private static function corridorCandidates($a, $b)
    {
        $distance = $a->distanceTo($b);
        if ($distance < 2) return array();

        $paths = array();
        self::walk($a, $b, $distance, array(), $paths);

        foreach ($paths as &$path) self::sortHexes($path);
        unset($path);

        return $paths;
    }

    /* One step of the enumeration: from $current, take every neighbour that is one hex CLOSER to
       $target and recurse. $remaining is the distance still to travel, so $remaining == 1 means
       the next step is the target itself and the corridor is complete. */
    private static function walk($current, $target, $remaining, array $sofar, array &$paths)
    {
        if ($remaining <= 1) {
            $paths[] = $sofar;
            return;
        }

        foreach (Mathlib::getNeighbouringHexes($current, 1) as $neighbour) {
            $hex = new OffsetCoordinate((int)$neighbour['q'], (int)$neighbour['r']);
            if ($hex->distanceTo($target) != $remaining - 1) continue;

            $next = $sofar;
            $next[] = $hex;
            self::walk($hex, $target, $remaining - 1, $next, $paths);
        }
    }

    /* ---------------------------------------------------------------- closed areas --- */

    /**
     * "If several ships linking up in such a manner form a closed area, the area may be 'filled
     * in' with an EDF as long as the filled-in hexes number less than double the total number of
     * Energy Draining Nets."
     *
     * ⚠️⚠️ **"FORM A CLOSED AREA" MEANS THE LINKS MUST ACTUALLY CLOSE — A CHAIN IS NOT AN AREA.**
     * This is the bug play testing found in game 4338 (user, 2026-09-05). Three Waymarkers stood
     * at (1,2), (0,0) and (1,-3): #1-#2 linked at 2 hexes and #2-#3 at 3, but #1-#3 were 5 apart,
     * so the three of them were a CHAIN, not a ring. The first build filled it anyway - it asked
     * only "are three or more Nets connected?" - and painted hexes like (1,0) that lie beside the
     * chain rather than inside anything. A connected group of N Nets with only N-1 links is a
     * tree: it encloses nothing, and the corridors are the whole of its field.
     *
     * So the area is the group's **2-CORE**: repeatedly drop any Net with fewer than two links
     * until none is left to drop. A chain erases itself completely; a ring survives whole; a ring
     * with a Net trailing off it keeps the ring and drops the trailer, which is right for the same
     * reason - the trailer is joined to the area by a corridor, it is not part of its boundary.
     * ⭐ That single loop replaces both "is there a cycle" and "which Nets bound the area", and it
     * needs no bridge-finding or biconnected-component machinery to do it.
     *
     * The cap is read as 2N-1 ("less than double") where N counts the Nets **of the surviving
     * core** - those are the ones that form the area, so neither a second formation elsewhere in
     * the fleet nor a trailing Net buys this one a bigger fill.
     *
     * ⚠️ OVER THE CAP MEANS FILL NOTHING, and the reason is recorded in self::$refusals. Filling a
     * partial area would need a rule for WHICH hexes get dropped, and any such rule is a rule the
     * sheet does not have — a partially filled area is worse than an unfilled one because it
     * looks deliberate.
     *
     * ⚠️ COLLINEAR NETS: the geometry is HexZone's rather than a fresh point-in-polygon because
     * convexHull discards collinear middles, leaving a two-point "hull" that pointInPolygon
     * rejects out of hand, and HexZone::containsUnit already carries the edge-walk that answers it
     * correctly (it is the Gravitic Mine shearing zone, which had to solve exactly this). It also
     * gives "the hull TOUCHES the hex" for free, which is the reading that matches the corridor
     * rule — a hex the area clips is in the area. ⚠️ Note this is now only reachable for a RING
     * whose Nets happen to be collinear, which a ring cannot be; the edge-walk stays because
     * containsUnit is shared code and must keep answering that case correctly for its other caller.
     */
    private static function fillClosedAreas(array $teamNets, array $links, $team, array &$coverage, array &$added)
    {
        $count = count($teamNets);
        $seen = array();

        for ($start = 0; $start < $count; $start++) {
            if (isset($seen[$start])) continue;

            //Depth-first walk of the link graph. Iterative, so a long chain cannot recurse deep.
            $group = array();
            $stack = array($start);
            $seen[$start] = true;

            while (!empty($stack)) {
                $index = array_pop($stack);
                $group[] = $index;
                if (!isset($links[$index])) continue;
                foreach ($links[$index] as $neighbour => $ignored) {
                    if (isset($seen[$neighbour])) continue;
                    $seen[$neighbour] = true;
                    $stack[] = $neighbour;
                }
            }

            //Only the Nets that actually CLOSE the area bound it - see the note above.
            $group = self::closedCore($group, $links);

            if (count($group) < self::FILL_MIN_NETS) continue;

            sort($group);                         //attribution and the bounding box must not depend on the DFS order

            $positions = array();
            foreach ($group as $index) $positions[] = $teamNets[$index]['pos'];
            $shipId = (int)$teamNets[$group[0]]['ship']->id;

            $cap = 2 * count($group) - 1;         //"less than double the total number of Nets"

            $candidates = self::areaCandidates($positions, $team, $coverage);
            if ($candidates === null) continue;   //sweep refused, already logged

            if (count($candidates) > $cap) {
                self::$refusals[] = 'team ' . $team . ': ' . count($group)
                                  . ' linked Nets enclose ' . count($candidates)
                                  . ' unfilled hexes, over the cap of ' . $cap . ' - area left unfilled';
                continue;
            }

            foreach ($candidates as $hex) self::addHex($added, $coverage, $hex, $team, $shipId);
        }
    }

    /* The 2-CORE of a connected group: what is left after repeatedly dropping every Net with
       fewer than two links inside the group. That is exactly the set of Nets that lie on a cycle,
       which is exactly "the ships linking up form a closed area".

         chain A-B-C          -> A and C have one link each, drop both; B is then isolated, drop
                                 it too. Nothing left, no area. (Game 4338.)
         ring A-B-C-A         -> every Net has two links, nothing is dropped, the ring is the area.
         ring + trailer D-A   -> D has one link and goes; A drops to two and stays. The ring is the
                                 area and D reaches it by corridor, which is what it did anyway.

       ⚠️ The pruning has to ITERATE, not run once: dropping a chain's endpoints leaves its middle
       with no links at all, and a single pass would keep it and hand a one-Net "area" to the hull.
       Degrees are recounted against the SURVIVORS on every pass, which is what makes a long tail
       unravel to nothing rather than one link shorter. */
    private static function closedCore(array $group, array $links)
    {
        $inCore = array();
        foreach ($group as $index) $inCore[$index] = true;

        $changed = true;
        while ($changed) {
            $changed = false;
            foreach (array_keys($inCore) as $index) {
                $degree = 0;
                if (isset($links[$index])) {
                    foreach ($links[$index] as $neighbour => $ignored) {
                        if (isset($inCore[$neighbour])) $degree++;
                    }
                }
                if ($degree < 2) {
                    unset($inCore[$index]);
                    $changed = true;
                }
            }
        }

        return array_keys($inCore);
    }

    /* The hexes a group's area would fill: inside or touching the hull of the Net positions, and
       NOT already covered by this team's field. Returns null when the sweep is refused.

       The bounding box is grown by one hex on every side because containsUnit() counts a hex the
       hull merely TOUCHES, which can be a hex whose centre lies outside the Nets' own extent. */
    private static function areaCandidates(array $positions, $team, array &$coverage)
    {
        $minQ = $maxQ = $positions[0]->q;
        $minR = $maxR = $positions[0]->r;
        foreach ($positions as $pos) {
            if ($pos->q < $minQ) $minQ = $pos->q;
            if ($pos->q > $maxQ) $maxQ = $pos->q;
            if ($pos->r < $minR) $minR = $pos->r;
            if ($pos->r > $maxR) $maxR = $pos->r;
        }
        $minQ--; $maxQ++; $minR--; $maxR++;

        $sweep = ($maxQ - $minQ + 1) * ($maxR - $minR + 1);
        if ($sweep > self::MAX_FILL_SWEEP) {
            self::$refusals[] = 'team ' . $team . ': refused a closed-area sweep of ' . $sweep . ' hexes';
            return null;
        }

        $candidates = array();
        for ($r = $minR; $r <= $maxR; $r++) {
            for ($q = $minQ; $q <= $maxQ; $q++) {
                $key = $q . ',' . $r;
                if (isset($coverage[$key][$team])) continue;   //already this team's field - free, and nothing to add
                $hex = new OffsetCoordinate($q, $r);
                if (!HexZone::containsUnit($hex, $positions)) continue;
                $candidates[$key] = $hex;
            }
        }

        return $candidates;
    }

    /* ---------------------------------------------------------------- helpers -------- */

    /* Record one hex for the caller AND mark it covered, so the next pair of Nets in this run
       sees it as existing field rather than as new. Idempotent: a hex this team already covers
       is dropped, which is what keeps two pairs sharing a corridor from adding it twice. */
    private static function addHex(array &$added, array &$coverage, $hex, $team, $shipId)
    {
        $key = $hex->q . ',' . $hex->r;
        if (isset($coverage[$key][$team])) return;

        if (!isset($coverage[$key])) $coverage[$key] = array();
        $coverage[$key][$team] = 1;

        $added[] = array('q' => $hex->q, 'r' => $hex->r, 'team' => (int)$team, 'shipId' => (int)$shipId);
    }

    /* WHERE EVERY UNIT ON THE BOARD IS: "q,r" => array(team => how many). Only the corridor
       tie-break reads it, and only when two candidate corridors survive rule 1 — so it is built
       lazily and at most once per resolve().
       The same three exclusions setEdfHexes() applies to field SOURCES apply to the units this
       counts: a destroyed unit, one still in hyperspace and one with no position are not
       standing in any corridor. */
    private static function buildOccupancy($gamedata)
    {
        $occupancy = array();

        foreach ($gamedata->ships as $unit) {
            if ($unit->isDestroyed()) continue;
            if ($unit->isReinforcement()) continue;
            if (!isset($unit->team)) continue;

            $pos = $unit->getHexPos();
            if (!$pos) continue;

            $key = $pos->q . ',' . $pos->r;
            $team = (int)$unit->team;
            if (!isset($occupancy[$key])) $occupancy[$key] = array();
            if (!isset($occupancy[$key][$team])) $occupancy[$key][$team] = 0;
            $occupancy[$key][$team]++;
        }

        return $occupancy;
    }

    private static function sortHexes(array &$hexes)
    {
        usort($hexes, function($a, $b){
            if ($a->q != $b->q) return ($a->q < $b->q) ? -1 : 1;
            if ($a->r != $b->r) return ($a->r < $b->r) ? -1 : 1;
            return 0;
        });
    }

    /* Lexicographic over two SORTED hex lists, numerically per coordinate. Numerically rather
       than on a joined string, because a string compare puts "-10,0" before "-2,0" and the
       tie-break would then depend on where on the map the fleet happens to be. */
    private static function compareHexes(array $a, array $b)
    {
        $shared = min(count($a), count($b));
        for ($i = 0; $i < $shared; $i++) {
            if ($a[$i]->q != $b[$i]->q) return ($a[$i]->q < $b[$i]->q) ? -1 : 1;
            if ($a[$i]->r != $b[$i]->r) return ($a[$i]->r < $b[$i]->r) ? -1 : 1;
        }
        if (count($a) == count($b)) return 0;
        return (count($a) < count($b)) ? -1 : 1;
    }
}
?>
