language: ruby
sudo: false
rvm:
  - 2.3.7
  - 2.4.5
  - 2.5.3
  - 2.6.5
  - 2.7.1
  - ruby-head
  - jruby-head
  - rbx-3.107

install: gem install net-ssh test-unit mocha

script: rake test

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3.107
