<?php
/**
 * ShipCompactor — the single source of truth for shrinking static ship payloads.
 *
 * WHY THIS FILE EXISTS
 * These routines used to be duplicated verbatim in generateStaticShipFile.php (dev/Docker)
 * and generateStaticShipFileWeb.php (live). Both copies carried a comment demanding they be
 * kept byte-identical, and they still drifted: eight keys were stripped locally and kept
 * live until 2026-08-01, so for months the live server shipped a bigger file to every
 * visitor than the dev box ever produced. A comment cannot enforce that invariant; one
 * shared file can. Add a rule here and BOTH generators get it.
 *
 * NOT autoloaded: source/autoload.php is an autogenerated classmap marked "do not edit",
 * so callers must require_once this file explicitly (same pattern global.php uses for
 * AssetLoader).
 */
class ShipCompactor
{
    /**
     * Strip default/empty values from ONE system's decoded JSON representation. Mirrors the
     * Optimisation #2 applied to the live gamedata payload in ShipSystem::stripForJson() —
     * the client's ShipSystem constructor re-applies these exact defaults on load, so
     * omitting them is safe.
     *
     * Fields removed when they equal their default:
     *   - Empty arrays : damage, criticals, fireOrders, power, specialAbilities, critData
     *   - Boolean false: destroyed, jsClass, boostable, canOffLine, fighter, preFires,
     *                    primary, isPrimaryTargetable, forceCriticalRoll,
     *                    advancedArmor, hardAdvancedArmor, fixedPower
     *   - Zero integers: outputMod, critRollMod
     *   - Null / empty string: outputDisplay, specialAbilityValue, imagePath, iconPath,
     *                          individualNotesTransfer, outputType
     *
     * The weapon loading/overload keys (turnsloadedArray, overloadturns, overloadshots,
     * extraoverloadshots, extraoverloadshotsArray, fireControlArray, rangeArray,
     * rangePenaltyArray, sustainedTarget) are safe on BOTH client paths:
     *   - blueprint use  : the Weapon constructor in model/shipSystem.js re-defaults every
     *                      one of them, and updateFiringModeData() guards each with
     *                      mathlib.arrayIsEmpty() before indexing it;
     *   - live instance  : systemFactory.js::createSystemFromJson DELETES them from the
     *                      merged blueprint (its `stateful` list) so the static value is
     *                      never read at all.
     * Do NOT add minDamageArray/maxDamageArray here — they are never empty in practice, so
     * there is nothing to win and they carry real data.
     *
     * RECURSION: a system may itself hold a `systems` array — a Fighter/flight entry sitting
     * in ship->systems carries its own ammoMagazine, weapons and so on. Before 08.2026 those
     * nested systems were never compacted at all (1,012 of them across 363 ship classes kept
     * every default). They ARE safe to compact: the client builds them through
     * SystemFactory::createSystemFromJson -> new window[name](args, ship), i.e. the real
     * ShipSystem/Weapon constructor, so they get the same defaults as any top-level system.
     *
     * ship->fighters is deliberately NOT walked. Those entries are constructed by the Fighter
     * constructor in shipSystem.js, which copies staticFighter and the JSON verbatim and
     * applies NO defaults of its own — stripping a key there would leave it undefined.
     */
    public static function compactSystem(array $system): array
    {
        // Empty arrays
        $emptyArrayKeys = ['damage','criticals','fireOrders','power','specialAbilities','critData',
                           'revealedTeams',
                           'turnsloadedArray','extraoverloadshotsArray','fireControlArray',
                           'rangeArray','rangePenaltyArray','sustainedTarget'];
        foreach ($emptyArrayKeys as $key) {
            if (isset($system[$key]) && is_array($system[$key]) && empty($system[$key])) {
                unset($system[$key]);
            }
        }
        // Boolean false defaults
        $falseKeys = ['destroyed','jsClass','boostable','canOffLine','fighter','preFires',
                      'primary','isPrimaryTargetable','forceCriticalRoll',
                      'advancedArmor','hardAdvancedArmor','fixedPower',
                      'stowed','outputDoubled','splitArcs'];
        foreach ($falseKeys as $key) {
            if (isset($system[$key]) && $system[$key] === false) {
                unset($system[$key]);
            }
        }
        // Zero integer defaults
        $zeroKeys = ['outputMod','critRollMod',
                     'overloadturns','overloadshots','extraoverloadshots'];
        foreach ($zeroKeys as $key) {
            if (isset($system[$key]) && $system[$key] === 0) {
                unset($system[$key]);
            }
        }
        // Null / empty-string defaults
        $nullEmptyKeys = ['outputDisplay','specialAbilityValue','imagePath','iconPath',
                          'individualNotesTransfer','outputType',
                          'stowedArcStart','stowedArcEnd','repairRestrictedTo','linkedOrbital',
                          'structureHomeLocation','linkedFiringGroup','linkedFiringSpread'];
        foreach ($nullEmptyKeys as $key) {
            if (array_key_exists($key, $system) && ($system[$key] === null || $system[$key] === '')) {
                unset($system[$key]);
            }
        }

        // Nested systems (a flight entry's own ammoMagazine/weapons) — see RECURSION above.
        if (!empty($system['systems']) && is_array($system['systems'])) {
            foreach ($system['systems'] as $i => $subSystem) {
                if (is_array($subSystem)) {
                    $system['systems'][$i] = self::compactSystem($subSystem);
                }
            }
        }

        return $system;
    }

    /**
     * SHIP-level stripping.
     *
     * $serverOnlyShipKeys is not size-tuning for its own sake. The generators json_encode()
     * the RAW BaseShip object rather than going through BaseShip::stripForJson(), so every
     * public property declared on BaseShip lands in the payload whether the client wants it
     * or not. These six are Chameleon Sensor Suite server state; no client code reads any of
     * them (grep the client tree — zero hits), and on 2,554 ships they were ~450KB of pure
     * waste.
     *
     * (On a static blueprint these are always null/false — the disguise is chosen at purchase
     * and lives on the real ship in gamedata — so dropping them leaks nothing and hides
     * nothing. They are simply dead weight here.)
     *
     * ⚠️ Any future public server-only property added to BaseShip belongs in this list.
     */
    public static function compactShip(array $ship): array
    {
        $serverOnlyShipKeys = ['chameleonDisguiseClass','chameleonBlueprint','chameleonDisguisedForViewer',
                               'chameleonPhantom','chameleonIsPhantom','chameleonWeaponMap'];
        foreach ($serverOnlyShipKeys as $key) {
            unset($ship[$key]);
        }

        if (!empty($ship['systems'])) {
            foreach ($ship['systems'] as $i => $system) {
                if (is_array($system)) {
                    $ship['systems'][$i] = self::compactSystem($system);
                }
            }
        }
        return $ship;
    }

    /**
     * Convenience wrapper: take a live ship OBJECT and return its compacted array form,
     * doing the encode/decode round-trip the compaction rules require (they operate on
     * decoded arrays, not on BaseShip instances — json_encode is also what filters out the
     * protected/private properties).
     */
    public static function compactShipObject($ship)
    {
        $arr = json_decode(json_encode($ship, JSON_PARTIAL_OUTPUT_ON_ERROR | JSON_UNESCAPED_UNICODE), true);
        return is_array($arr) ? self::compactShip($arr) : $ship;
    }

    /**
     * Pre-compress a generated static file to <file>.br.
     *
     * WHY PRE-COMPRESS, rather than compress per request:
     * these files change only on deploy, so the cost is paid once here instead of on every
     * visitor, which lets us use a far higher quality than an on-the-fly filter could
     * afford. Measured on real ship data (4.34MB faction file):
     *     gzip -6    281KB  0.07s      <- what .htaccess mod_deflate does today
     *     brotli q5   43KB  0.06s
     *     brotli q9   39KB  0.11s      <- what we use
     *     brotli q11  36KB  2.84s
     *
     * QUALITY 9, DELIBERATELY NOT 11. q9 lands within 8% of q11's size for roughly 1/25th
     * the time. These generators run inside a LiteSpeed web request with a documented
     * history of workers being killed on long runs (see the memory_limit note at the top of
     * generateStaticShipFileWeb.php) — a slow compression step is exactly the kind of thing
     * that reintroduces the intermittent 503. Brotli's window size (lgwin) made no
     * measurable difference on this data, so PHP's binding exposing no lgwin costs nothing.
     *
     * STALE-FILE SAFETY: the .br is unlinked FIRST and only replaced via an atomic rename at
     * the very end. A leftover .br from a previous run would be served in preference to the
     * freshly written source (by the mod_rewrite block in source/public/.htaccess, or by
     * gamelobbyloader.php) — i.e. every visitor would silently get OLD ship data while the
     * source file on disk looked current. Failing closed (no .br, gzip fallback) is always
     * correct; a stale .br is not.
     *
     * Returns the .br path on success, or null if the brotli extension is unavailable (the
     * Docker/dev box has no brotli — callers then simply fall back to gzip).
     */
    public static function precompressBrotli(string $path, int $quality = 9): ?string
    {
        @unlink($path . '.br');
        if (!function_exists('brotli_compress_init') || !function_exists('brotli_compress_add')) {
            return null;
        }
        if (!is_readable($path)) {
            return null;
        }

        $in = @fopen($path, 'rb');
        if (!$in) return null;
        $tmp = $path . '.br.tmp';
        $out = @fopen($tmp, 'wb');
        if (!$out) { fclose($in); return null; }

        // Incremental API so a large file never has to land in a PHP string — the same
        // reason the Web generator spools faction fragments to disk instead of building one
        // big array. Peak memory here is one 1MB chunk plus brotli's own window.
        $ctx = brotli_compress_init($quality, BROTLI_TEXT);
        if ($ctx === false) { fclose($in); fclose($out); @unlink($tmp); return null; }

        while (!feof($in)) {
            $chunk = fread($in, 1 << 20); // 1MB
            if ($chunk === false || $chunk === '') break;
            $encoded = brotli_compress_add($ctx, $chunk, BROTLI_PROCESS);
            if ($encoded === false) { fclose($in); fclose($out); @unlink($tmp); return null; }
            fwrite($out, $encoded);
        }
        $tail = brotli_compress_add($ctx, '', BROTLI_FINISH);
        if ($tail === false) { fclose($in); fclose($out); @unlink($tmp); return null; }
        fwrite($out, $tail);

        fclose($in);
        fclose($out);

        if (!@rename($tmp, $path . '.br')) { @unlink($tmp); return null; }
        return $path . '.br';
    }
}
