<?php
/**
 * ShipCompactor — the single source of truth for shrinking static ship payloads.
 *
 * WHY THIS FILE EXISTS
 * These routines used to be duplicated verbatim in generateStaticShipFile.php (dev/Docker)
 * and generateStaticShipFileWeb.php (live). Both copies carried a comment demanding they be
 * kept byte-identical, and they still drifted: eight keys were stripped locally and kept
 * live until 2026-08-01, so for months the live server shipped a bigger file to every
 * visitor than the dev box ever produced. A comment cannot enforce that invariant; one
 * shared file can. Add a rule here and BOTH generators get it.
 *
 * NOT autoloaded: source/autoload.php is an autogenerated classmap marked "do not edit",
 * so callers must require_once this file explicitly (same pattern global.php uses for
 * AssetLoader).
 */
class ShipCompactor
{
    /**
     * SYSTEM keys NO CLIENT CODE READS — dropped whatever their value, not just at their default.
     *
     * WHY THIS EXISTS (JUMP_POINTS_PLAN.md section 8, "A"). Both generators json_encode the RAW
     * system objects rather than going through ShipSystem::stripForJson(), so every public
     * property a system declares lands in the static blueprint whether the browser has any use
     * for it or not. Measured 2026-08-24 over all 93 faction files / 56,687 system objects, these
     * 115 keys are 9.48MB of a 97.8MB tree — the single largest block of pure waste in it, and
     * the lowest-risk to remove: a key nothing reads cannot break anything.
     *
     * ⭐ THE GREP IS THE WHOLE TEST — re-run it before adding to this list, and before trusting it.
     *   grep -rlw --exclude-dir=static -- '<key>' source/public
     * The tree searched is source/public in full: the client JS, the React sources under
     * client/UI/reactJs, the three BUILT bundles (game.legacy, gamelobby.legacy, UI.bundle — a
     * bundle can only contain what its sources contain, but they are cheap insurance against a
     * source file that is no longer wired up) and every .php page that emits inline JS. A hit
     * anywhere means the key stays.
     *
     * TWO TRAPS THE NAIVE GREP FALLS INTO, both hit while compiling this list:
     *  1. WORD BOUNDARIES MATTER (-w). A plain substring grep for `useOEW` matches
     *     `useOEWArray`, and for `rof` matches `profile`, so 'has hits' is not the same question
     *     as 'is read'. Conversely -w alone flagged `inadequate`, `squadrons` and `rakes` as read
     *     — those hits are English prose in factions-tiers.php, and `rof` matched bytes inside
     *     notali.png. Read the hits; do not just count them.
     *  2. A KEY CAN BE WRITE-ONLY. `grouping` and `rangeDamagePenalty` DO appear in the client,
     *     but their only appearance — source and bundles alike — is the guarded assignment
     *     `arrayIsEmpty(this.groupingArray) || (this.grouping = this.groupingArray[mode])`.
     *     Nothing ever reads the result back, so both are dead despite matching. 0.80MB.
     *
     * AND THE ONE DYNAMIC READ IN THE CLIENT: weaponManager.getModeFlag() does
     * `weapon[flagName + 'Array']`. Its call sites pass three string literals only —
     * 'doNotIntercept', 'hextarget', 'uninterceptable' — all three of which the grep already
     * finds spelled out in shipSystem.js. Nothing else composes a system property name, so the
     * name-by-name grep is sound. If a second dynamic reader is ever added, this list needs
     * re-auditing (that is why it is called out here rather than left to be rediscovered).
     *
     * Biggest entries: overkillArcStructures 1.55MB, addedByEnhancement 1.45MB, hitChartName
     * 1.07MB, revealAfterPreFire 0.59MB, rangeDamagePenalty 0.51MB, noPrimaryHits 0.48MB,
     * doOverkill / noOverkill 0.42MB each, isLinked / useOEWArray 0.37MB each, grouping 0.29MB.
     * Most of the rest are server-side working state (escape pods, Shadow attachment, jamming
     * and rail cooldown counters, vortex bookkeeping, pending-transfer slots) that has no reason
     * to be on a blueprint at all.
     *
     * ⚠️ Stored as a KEY=>true map, not a list: compactSystem does one array_diff_key() rather
     * than 115 isset() probes per system, which over 56,687 systems is the difference between a
     * free rule and a measurable slice of the deploy generator's runtime (see
     * arch_static_generator_streaming — this runs inside a LiteSpeed request).
     *
     * A handful of these (jsClass, advancedArmor, hardAdvancedArmor, forceCriticalRoll,
     * specialAbilityValue, stowedArcEnd, linkedOrbital) also still appear in the value-based
     * lists below, where they were added earlier for their default value alone. That is
     * deliberate, not an oversight: this pass has already removed them by the time those loops
     * run, so the duplicates are no-ops — but each carries the rationale for why it was safe at
     * its default, and deleting the entry would delete the reasoning with it.
     */
    private static $deadSystemKeys = null;

    private static function deadSystemKeys(): array
    {
        if (self::$deadSystemKeys !== null) return self::$deadSystemKeys;

        $keys = ['overkillArcStructures','addedByEnhancement','hitChartName','revealAfterPreFire',
                 'rangeDamagePenalty','noPrimaryHits','doOverkill','noOverkill',
                 'isLinked','useOEWArray','grouping','thrustused',
                 'rof','orbitalBump','pendingLcvDeployStartTransfer','pendingDeployStartTransfer',
                 'linkedOrbital','maxpulsesArray','inadequateLoadedRolls','specialAbilityValue',
                 'inadequateLoadedTurn','usagePopulated','escapeRolled','shadowStructLost',
                 'shadowLaunched','shadowAttached','inadequate','maxpulses',
                 'escapeNames','shadowCutOff','escapeTotal','squadrons',
                 'escapeRoll','escapeMax','fixedBonusPulsesArray','firstCriticalIgnored',
                 'mineRangeArray','useDieArray','fixedBonusPulses','rofArray',
                 'activeVortexId','vortexOpenTurn','vortexCloseTurn','mineRange',
                 'normaload','missileRackReloadedTurn','useDie','doCountForCombatValue',
                 'marinesReloadedTurn','jammingLoadedValue','jammingLoadedTurn','alreadyConsidered',
                 'forceCriticalRoll','hardAdvancedArmor','onMine','advancedArmor',
                 'startingAmmo','jsClass','animationWidth2','rangeDamagePenaltyPBolter',
                 'maxRepairPoints','usedRepairPoints','railCritLoadedValue','setRanges',
                 'isCloaked','railCritLoadedTurn','systemHitChart','ballisticWeapon',
                 'usedThisTurn','curDamage','powerReceivedFromFrontEnd','fireControlMod',
                 'powerReceivedFromBackEnd','mineWeapons','subChartWhileDocked','setShipTypes',
                 'hasSystemHitChart','addedDice','blueprintRating','canRegenerate',
                 'powerDrawnAtFiring','haphazardTargeting','changeThisTurn','testRun',
                 'worksOnAllFactions','basicDistanceRange','bonusType','escortArray',
                 'flashDamage','worksOnlyOnBaseHull','rakes','basicRange',
                 'presetSubordinates','worksOnFighters','damageBonus','showHexagonArc',
                 'worksOnAllies','blueprintMaxhealth','initiativeBonus','worksOnShips',
                 'specTotalSelected','currchangedSpec','capacityBonus','totalBaseRating',
                 'firstShotMissed','transferQueue','blastersRequiredArray','postArmorTotal',
                 'reduceFacing','stowedArcEnd','exlusive','lastCalculatedDamage',
                 'bonusDamageShots','reduceStructure','reduceSystem'];

        self::$deadSystemKeys = array_fill_keys($keys, true);
        return self::$deadSystemKeys;
    }

    /**
     * Strip default/empty values from ONE system's decoded JSON representation. Mirrors the
     * Optimisation #2 applied to the live gamedata payload in ShipSystem::stripForJson() —
     * the client's ShipSystem constructor re-applies these exact defaults on load, so
     * omitting them is safe.
     *
     * Fields removed when they equal their default:
     *   - Empty arrays : damage, criticals, fireOrders, power, specialAbilities, critData
     *   - Boolean false: destroyed, jsClass, boostable, canOffLine, fighter, preFires,
     *                    primary, isPrimaryTargetable, forceCriticalRoll,
     *                    advancedArmor, hardAdvancedArmor, fixedPower
     *   - Zero integers: outputMod, critRollMod
     *   - Null / empty string: outputDisplay, specialAbilityValue, imagePath, iconPath,
     *                          individualNotesTransfer, outputType
     *
     * The weapon loading/overload keys (turnsloadedArray, overloadturns, overloadshots,
     * extraoverloadshots, extraoverloadshotsArray, fireControlArray, rangeArray,
     * rangePenaltyArray, sustainedTarget) are safe on BOTH client paths:
     *   - blueprint use  : the Weapon constructor in model/shipSystem.js re-defaults every
     *                      one of them, and updateFiringModeData() guards each with
     *                      mathlib.arrayIsEmpty() before indexing it;
     *   - live instance  : systemFactory.js::createSystemFromJson DELETES them from the
     *                      merged blueprint (its `stateful` list) so the static value is
     *                      never read at all.
     * Do NOT add minDamageArray/maxDamageArray here — they are never empty in practice, so
     * there is nothing to win and they carry real data.
     *
     * RECURSION: a system may itself hold a `systems` array — a Fighter/flight entry sitting
     * in ship->systems carries its own ammoMagazine, weapons and so on. Before 08.2026 those
     * nested systems were never compacted at all (1,012 of them across 363 ship classes kept
     * every default). They ARE safe to compact: the client builds them through
     * SystemFactory::createSystemFromJson -> new window[name](args, ship), i.e. the real
     * ShipSystem/Weapon constructor, so they get the same defaults as any top-level system.
     *
     * ship->fighters is deliberately NOT walked. Those entries are constructed by the Fighter
     * constructor in shipSystem.js, which copies staticFighter and the JSON verbatim and
     * applies NO defaults of its own — stripping a key there would leave it undefined.
     *
     * ── THE SAFETY ARGUMENT, AND WHY IT IS NOT "the constructor re-defaults everything" ──────
     * Worth being precise, because the obvious reading of the paragraph above is wrong. The
     * client's ShipSystem/Weapon constructors copy the JSON verbatim (`for (var i in json)
     * this[i] = json[i]`) and then re-default exactly the twenty-one named properties listed at
     * the top of this comment — and nothing else. Every weapon subclass below Weapon is a bare
     * three-liner that adds no defaults at all. So for any key beyond that list the test is not
     * "does something restore it" but:
     *
     *      does EVERY read site behave identically when the value is `undefined`?
     *
     * For a `false` that means every read must be a truthy test. `undefined` is falsy, so
     * `if (sys.foo)`, `!sys.foo`, `Boolean(sys.foo)` and `sys.foo === true` are all identical —
     * but `sys.foo === false` and `sys.foo == false` are NOT (`undefined == false` is false).
     * For an empty array it means every read must be `mathlib.arrayIsEmpty()` (a for..in, which
     * is a no-op on undefined), optional chaining, or an `x && x[i]` guard — never a bare
     * `.length`, index or `.forEach`.
     *
     * FOUR AUDITED EXCLUSIONS. These look exactly like the keys around them and are NOT
     * strippable; they are written down because the next person will measure the same tempting
     * numbers and needs to know they were already checked:
     *   - isTargetable (0.13MB of `false`) — SystemInfoButtons.js isPseudoSystem does
     *     `system.isTargetable === false`. Absent would turn every ability system into a real
     *     SCS box. (weaponManager.js's `!= true` is fine; the `=== false` is what kills it.)
     *   - pressignedReset — baseSystems.js:1760 `this.pressignedReset == false`.
     *   - animationArray / animationColorArray (0.97MB of `[]`) — the guarded copies in
     *     updateFiringModeData are not the only readers.
     *     AllWeaponFireAgainstShipAnimation.js does a BARE
     *     `weapon.animationArray[incomingFire.firingMode] || weapon.animation`, which becomes
     *     `undefined[...]` — a TypeError in the middle of the firing animation — the moment the
     *     key is absent rather than empty.
     *   - startArcArray / endArcArray (0.79MB of `[]`) — molecular.js:756 and particle.js:22 do
     *     a bare `this.startArcArray.length > 0` in the constructor and special.js:878 indexes
     *     [0] directly. (systems.js uses `?.length`, which would have been fine; one unguarded
     *     reader is enough.)
     *
     * ── AND WHY THERE IS NO GENERIC null / 0 PASS (JUMP_POINTS_PLAN.md section 8 "D") ────────
     * 5.7MB of `null` and 5.1MB of `0` sit in the tree and every large candidate failed its
     * audit, which is precisely the argument for auditing each key rather than writing a rule:
     *   boostEfficiency (1.06MB) has `.toString()` called on it in power.js · maxBoostLevel
     *   (1.05MB) is returned into arithmetic, where null coerces to 0 and undefined to NaN ·
     *   turnsloaded (0.40MB) is concatenated unconditionally into data["Loading"] and reaches
     *   Math.max · distanceRange (0.37MB) and normalload (0.32MB) both reach a bare
     *   Math.max(a, b) · maxVariableShots (0.46MB) is `++`-ed · thrustwasted (0.17MB) is
     *   `-=`-ed · rangePenalty (0.11MB) is multiplied · and powerReq / output / location /
     *   armour all MEAN zero (movement.js:1477 keys off `system.armour === undefined`).
     * The zeros and nulls that WERE safe to drop are the ones nothing reads, and those have
     * already gone via $deadSystemKeys.
     */
    public static function compactSystem(array $system): array
    {
        // Keys no client code reads at all — see $deadSystemKeys. One array_diff_key rather
        // than 115 isset() probes per system, and done FIRST so the value-based passes below
        // walk a smaller array.
        $system = array_diff_key($system, self::deadSystemKeys());

        // Empty arrays
        $emptyArrayKeys = ['damage','criticals','fireOrders','power','specialAbilities','critData',
                           'revealedTeams',
                           'turnsloadedArray','extraoverloadshotsArray','fireControlArray',
                           'rangeArray','rangePenaltyArray','sustainedTarget',
                           /* Per-firing-mode arrays. Every reader is an
                              `if (!mathlib.arrayIsEmpty(x)) ...` in updateFiringModeData, or one
                              of the `x && x[mode]` / `for..in` variants in FiringModeSelector and
                              weaponManager's shortest-load scan, and arrayIsEmpty is a for..in,
                              which is a no-op on undefined. 11.8MB. See the four exclusions
                              above before adding animation/arc arrays to this list. */
                           'specialHitChanceCalculationArray','specialRangeCalculationArray',
                           'rangeDamagePenaltyArray','uninterceptableArray','ignoreJinkingArray',
                           'doNotInterceptArray','calledShotModArray','noLockPenaltyArray',
                           'distanceRangeArray','canSplitShotsArray','autoFireOnlyArray',
                           'defaultShotsArray','ignoreAllEWArray','modeLettersArray',
                           'loadingtimeArray','weaponClassArray','hidetargetArray',
                           'hextargetArray','damageTypeArray','groupingArray','rakingArray',
                           'priorityArray','shotsArray','gunsArray'];
        foreach ($emptyArrayKeys as $key) {
            if (isset($system[$key]) && is_array($system[$key]) && empty($system[$key])) {
                unset($system[$key]);
            }
        }
        // Boolean false defaults
        $falseKeys = ['destroyed','jsClass','boostable','canOffLine','fighter','preFires',
                      'primary','isPrimaryTargetable','forceCriticalRoll',
                      'advancedArmor','hardAdvancedArmor','fixedPower',
                      'stowed','outputDoubled','splitArcs',
                      /* Weapon/system capability flags. Every read site in the client is a
                         truthy test — verified one key at a time, the audit being a grep for
                         `=== false`, `!== false`, `== false` and `!= false` across the whole of
                         source/public. 17.9MB, the biggest single win here. isTargetable and
                         pressignedReset are the two that failed that grep; see above. */
                      'privateRepairOnly','hideInShipWindow','specialHitChanceCalculation',
                      'canInterceptUninterceptable','specialRangeCalculation',
                      'noInterceptDegradation','doInterceptDegradation','freeinterceptspecial',
                      'doubleRangeIfNoLock','alwaysoverloading','ballisticIntercept',
                      'canModesIntercept','checkAmmoMagazine','canChangeShots','ignoreJinking',
                      'canSplitShots','freeintercept','isRammingAttack','overloadable',
                      'canTargetAll','autoFireOnly','ignoreAllEW','uninterceptable',
                      'doNotIntercept','ignoresLoS','isModified','hidetarget','exclusive',
                      'noProjectile','hextarget','ballistic','excludeFromDefaultShuttles',
                      'designedToRam','noLockPenalty','useOEW'];
        foreach ($falseKeys as $key) {
            if (isset($system[$key]) && $system[$key] === false) {
                unset($system[$key]);
            }
        }
        // Zero integer defaults
        $zeroKeys = ['outputMod','critRollMod',
                     'overloadturns','overloadshots','extraoverloadshots'];
        foreach ($zeroKeys as $key) {
            if (isset($system[$key]) && $system[$key] === 0) {
                unset($system[$key]);
            }
        }
        // Null / empty-string defaults
        $nullEmptyKeys = ['outputDisplay','specialAbilityValue','imagePath','iconPath',
                          'individualNotesTransfer','outputType',
                          'stowedArcStart','stowedArcEnd','repairRestrictedTo','linkedOrbital',
                          'structureHomeLocation','linkedFiringGroup','linkedFiringSpread'];
        foreach ($nullEmptyKeys as $key) {
            if (array_key_exists($key, $system) && ($system[$key] === null || $system[$key] === '')) {
                unset($system[$key]);
            }
        }

        // Nested systems (a flight entry's own ammoMagazine/weapons) — see RECURSION above.
        if (!empty($system['systems']) && is_array($system['systems'])) {
            foreach ($system['systems'] as $i => $subSystem) {
                if (is_array($subSystem)) {
                    $system['systems'][$i] = self::compactSystem($subSystem);
                }
            }
        }

        return $system;
    }

    /**
     * SHIP-level stripping.
     *
     * $serverOnlyShipKeys is not size-tuning for its own sake. The generators json_encode()
     * the RAW BaseShip object rather than going through BaseShip::stripForJson(), so every
     * public property declared on BaseShip lands in the payload whether the client wants it
     * or not. These six are Chameleon Sensor Suite server state; no client code reads any of
     * them (grep the client tree — zero hits), and on 2,554 ships they were ~450KB of pure
     * waste.
     *
     * (On a static blueprint these are always null/false — the disguise is chosen at purchase
     * and lives on the real ship in gamedata — so dropping them leaks nothing and hides
     * nothing. They are simply dead weight here.)
     *
     * ⚠️ Any future public server-only property added to BaseShip belongs in this list.
     */
    public static function compactShip(array $ship): array
    {
        /* preBattleDamage / preBattleAvailable are pre-battle-damage state that only ever
           exists on a ship the player has BOUGHT (the lobby authors it, the buy POST carries
           it, loadSavedFleet fills it). On a blueprint they are always array()/null.
           Dropping them is not only 40-odd bytes x 2,554 ships: `array()` encodes as the
           JSON ARRAY [], and an array that later gets `sys`/`ftr` hung off it in the browser
           STRINGIFIES BACK AS [] - which is exactly how every authored point of pre-battle
           damage was lost on submit (fixed on the client side too, in battleDamage.get). */
        /* systemEnhancements is the same shape of thing for per-system refits
           (WEAPON_ENHANCEMENTS_PLAN.md §3.1): it only ever holds rows on a ship the player has
           BOUGHT, so on a blueprint it is always array(). systemEnhancementOffers - what MAY be
           bought - is NOT dropped: it is blueprint data and the lobby menu is built from it (D3).
           Dropping the purchased array also guarantees systemEnhancements.js creates a FRESH array
           per ship rather than inheriting one through a clone. */
        $serverOnlyShipKeys = ['chameleonDisguiseClass','chameleonBlueprint','chameleonDisguisedForViewer',
                               'chameleonPhantom','chameleonIsPhantom','chameleonWeaponMap',
                               'preBattleDamage','preBattleAvailable','systemEnhancements'];
        foreach ($serverOnlyShipKeys as $key) {
            unset($ship[$key]);
        }

        /* An Ancient/Primordial hull, a flight and a mine all offer no per-system refits, which is
           640 of the 2,557 classes carrying a bare `[]` for nothing. Same rule the empty-array pass
           in compactSystem applies; systemEnhancements.js treats absent and empty identically. */
        if (isset($ship['systemEnhancementOffers']) && is_array($ship['systemEnhancementOffers'])
            && empty($ship['systemEnhancementOffers'])) {
            unset($ship['systemEnhancementOffers']);
        }

        if (!empty($ship['systems'])) {
            foreach ($ship['systems'] as $i => $system) {
                if (is_array($system)) {
                    $ship['systems'][$i] = self::compactSystem($system);
                }
            }
        }
        return $ship;
    }

    /**
     * Convenience wrapper: take a live ship OBJECT and return its compacted array form,
     * doing the encode/decode round-trip the compaction rules require (they operate on
     * decoded arrays, not on BaseShip instances — json_encode is also what filters out the
     * protected/private properties).
     */
    public static function compactShipObject($ship)
    {
        $arr = json_decode(json_encode($ship, JSON_PARTIAL_OUTPUT_ON_ERROR | JSON_UNESCAPED_UNICODE), true);
        if (!is_array($arr)) return $ship;

        self::annotateSystems($ship->systems, $arr['systems']);
        return self::compactShip($arr);
    }

    /**
     * Copy PROTECTED system flags the client needs onto the decoded blueprint.
     *
     * json_encode is what drops protected properties, which is normally exactly right — but
     * a handful of them are rules the CLIENT has to reproduce, and the blueprint is the only
     * place it can learn them. The alternative (making the property public) is a trap this
     * codebase has hit before: a launcher's missileArray entries are raw weapon objects that
     * are json_encoded WHOLE rather than through ShipSystem::stripForJson, so a public flag
     * lands on every ammo entry of every live gamedata poll — see the comments on
     * $alwaysHideFireOrders / $hideFireOrdersFromEnemies in weapon.php. Reading it through an
     * accessor HERE keeps it to the static blueprint, which is the only consumer.
     *
     * Only survivesStructureDestruction so far, and only written when TRUE: the gamelobby's
     * pre-battle damage preview mirrors ShipSystem::isDestroyed's structure cascade itself
     * (battleDamage.cascadeStructure), and a shield projection must not go dark there when
     * its section's structure is destroyed.
     *
     * Walks $decoded by the keys of $systems: json_encode preserves an array's keys, so the
     * two are the same shape all the way down, nested flight subsystems included.
     */
    private static function annotateSystems($systems, array &$decoded)
    {
        if (!is_array($systems)) return;

        foreach ($systems as $key => $system) {
            if (!is_object($system) || !isset($decoded[$key]) || !is_array($decoded[$key])) continue;

            if (method_exists($system, 'getSurvivesStructureDestruction')
                && $system->getSurvivesStructureDestruction()) {
                $decoded[$key]['survivesStructureDestruction'] = true;
            }

            if (!empty($system->systems) && !empty($decoded[$key]['systems'])) {
                self::annotateSystems($system->systems, $decoded[$key]['systems']);
            }
        }
    }

    /**
     * Pre-compress a generated static file to <file>.br.
     *
     * WHY PRE-COMPRESS, rather than compress per request:
     * these files change only on deploy, so the cost is paid once here instead of on every
     * visitor, which lets us use a far higher quality than an on-the-fly filter could
     * afford. Measured on a real 4.15MB faction file:
     *     gzip -6    281KB  0.07s
     *     brotli q4   52KB  0.03s
     *     brotli q9   38KB  0.11s      <- what we use
     *     brotli q11  36KB  2.84s
     *
     * MIND THE BASELINE — the two consumers were NOT starting from the same place:
     *   - static/json/<faction>.json is served by gamelobbyloader.php, a PHP endpoint. It
     *     pulls in global.php, which registers fv_compress_output() (compression_helper.php)
     *     as a shutdown function, and that ALREADY brotli-compressed every response — at
     *     quality 4, recomputed on every single request. So here the win is q4 -> q9
     *     (~26% smaller) PLUS eliminating ~25ms of compression CPU per faction open.
     *   - a plain static .js served straight by Apache/LiteSpeed never reaches PHP, so its
     *     baseline really is mod_deflate gzip, and the win there is the full ~7x.
     * Do not quote the gzip figure for the JSON path; it flatters the result about 5x.
     *
     * QUALITY 9, DELIBERATELY NOT 11. q9 lands within 8% of q11's size for roughly 1/25th
     * the time. These generators run inside a LiteSpeed web request with a documented
     * history of workers being killed on long runs (see the memory_limit note at the top of
     * generateStaticShipFileWeb.php) — a slow compression step is exactly the kind of thing
     * that reintroduces the intermittent 503. Brotli's window size (lgwin) made no
     * measurable difference on this data, so PHP's binding exposing no lgwin costs nothing.
     *
     * STALE-FILE SAFETY: the .br is unlinked FIRST and only replaced via an atomic rename at
     * the very end. A leftover .br from a previous run would be served by gamelobbyloader.php
     * in preference to the freshly written .json — i.e. every visitor would silently get OLD
     * ship data while the source file on disk looked current. Failing closed (no .br, so the
     * existing runtime compression handles it) is always correct; a stale .br is not.
     *
     * Returns the .br path on success, or null if the brotli extension is unavailable (the
     * Docker/dev box has no brotli — callers then simply fall back to gzip).
     */
    public static function precompressBrotli(string $path, int $quality = 9): ?string
    {
        @unlink($path . '.br');

        // Check the CONSTANTS as well as the functions. Under PHP 8 a missing constant is a
        // fatal Error, not a notice — and this runs inside the deploy generator, so a fatal
        // here would abort the whole run partway through, leaving some faction files written
        // and others not. Different brotli bindings do not all expose the same constant
        // names, so verify rather than assume. If anything is missing we return null and the
        // caller silently keeps its existing runtime compression.
        if (!function_exists('brotli_compress_init') || !function_exists('brotli_compress_add')
            || !defined('BROTLI_TEXT') || !defined('BROTLI_PROCESS') || !defined('BROTLI_FINISH')) {
            return null;
        }
        if (!is_readable($path)) {
            return null;
        }

        $in = @fopen($path, 'rb');
        if (!$in) return null;
        $tmp = $path . '.br.tmp';
        $out = @fopen($tmp, 'wb');
        if (!$out) { fclose($in); return null; }

        // Incremental API so a large file never has to land in a PHP string — the same
        // reason the Web generator spools faction fragments to disk instead of building one
        // big array. Peak memory here is one 1MB chunk plus brotli's own window.
        $ctx = brotli_compress_init($quality, BROTLI_TEXT);
        if ($ctx === false) { fclose($in); fclose($out); @unlink($tmp); return null; }

        while (!feof($in)) {
            $chunk = fread($in, 1 << 20); // 1MB
            if ($chunk === false || $chunk === '') break;
            $encoded = brotli_compress_add($ctx, $chunk, BROTLI_PROCESS);
            if ($encoded === false) { fclose($in); fclose($out); @unlink($tmp); return null; }
            fwrite($out, $encoded);
        }
        $tail = brotli_compress_add($ctx, '', BROTLI_FINISH);
        if ($tail === false) { fclose($in); fclose($out); @unlink($tmp); return null; }
        fwrite($out, $tail);

        fclose($in);
        fclose($out);

        if (!@rename($tmp, $path . '.br')) { @unlink($tmp); return null; }
        return $path . '.br';
    }
}
